### ISSUE TITLE
Can you help me to solve my problem in your project? thx~

### ISSUE THREAD

**Issue by Smityz** [wuxie2015/tribody_chat#1]
你好，我是一名来自哈尔滨的大学生，最近要做一个课程设计，需要用到您这个开源项目的部分源码。但是在部署您的源项目的时候遇到了一些问题，请问可以给我提供一些帮助吗？

**Comment by wuxie2015** [comment]
谢谢看了我的代码，请问有什么可以帮到你的呢？
